version: '3'
services:
  control-panel-api:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: ${APP_ENV}
    image: control-panel-api
    container_name: lgsm-control-panel-api
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/app
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /app
    env_file:
      - .env
    networks:
      - lgsm-cp-network
    depends_on:
      - composer

  webserver:
    image: nginx:alpine
    container_name: lgsm-control-panel-webserver
    restart: unless-stopped
    tty: true
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_SSL_PORT}:443
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
      SERVER_NAME: ${SERVER_NAME}
      APP_NAME: ${APP_NAME}
    volumes:
      - ./src:/app
      - ./docker/nginx/conf.d/:/etc/nginx/templates/
    networks:
      - lgsm-cp-network
    depends_on:
      - lgsm-control-panel-api

  composer:
    image: composer:2.0
    env_file:
      - .env
    volumes:
      - ./src:/app
    working_dir: /app
    command: composer install --ignore-platform-reqs --no-scripts

  redis:
    image: "redis:alpine"
    command: redis-server
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - lgsm-cp-network

  migrator:
    image: lgsm-control-panel-api
    command: ["php", "/app/artisan", "migrate", '--force']
    env_file:
      - .env
    volumes:
      - ./src:/app
    networks:
      - lgsm-cp-network
    depends_on:
      - composer

#Docker Networks
networks:
  lgsm-cp-network:
    driver: bridge
